### PR TITLE
Refactor browsers.py

### PR DESCRIPTION
**Pull request by Mohamad1994HD**
browsers.py was refactored in a way that chrome as app infrastructure provider is used from chrome.py, make it possible to add integrability for other browsers as provider app in easier way.

### CODE REVIEW

**Comment by ChrisKnott** [comment]
Hi Mohamad - I haven't forgotten about this but haven't had a chance to look at it yet. Thanks for submitting the refactoring, it looks like a good idea for the future

**Comment by Mohamad1994HD** [comment]
Thanks a lot for feedback, just to mention it is my first
contribution-trial in open source projects .. I am looking forward to
improve my skills.

Thanks


On Feb 14, 2018 1:17 PM, "Chris Knott" <notifications@github.com> wrote:

Hi Mohamad - I haven't forgotten about this but haven't had a chance to
look at it yet. Thanks for submitting the refactoring, it looks like a good
idea for the future

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisKnott/Eel/pull/24#issuecomment-365572621>, or mute
the thread

**Comment by ThoughtfulDev** [comment]
Hi Mohamad, 
there is a small Error (which is also present in the current master) in your browser.py

in the `_chrome_win` function you try to catch the `WindowsError` and return `chrome_path` which in the exception case isn't even set. 

so it should be like this
```
def _chrome_win(self):
    ...
    except WindowsError:
        chrome_path = None

    return chrome_path
```

**Comment by ChrisKnott** [comment]
@ThoughtfulDev

Good spot, I will incorporate this and Mohamed's changes soon

**Comment by ChrisKnott** [comment]
@Mohamad1994HD 

I am really keen to incorporate your changes, because I think it's very important to encourage new developers, and more importantly your change is a good idea that demonstrates good forward thinking!

Unfortunately because I was so lazy in getting round to merging this, the codebase has moved on a bit. Do you think you could pull latest changes, then submit again.

As for feedback, my only comment is I don't think there's any need to use object orientation here. Python is a multi-paradigm language, and we only need to bring in the power of OO if it's a clear benefit. In this case, we are just packaging a set of functions together in order to hide some platform specific messiness from our main code. I would just leave it as top level function, where the other file calls chrome.get_instance() or whatever. Only use OO if there's a benefit to tracking the internal state of the object. In this case, I don't think there is.

Lastly, I like your example, but it should be on a separate pull request. If you split that one out, I will accept them both.

**Pull request closed without merging**
